services:
  db:
    image: postgres:16-alpine
    container_name: crm-postgres
    env_file:
      - crm/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: crm-redis
    ports:
      - "6379:6379"

  web:
    build: crm
    container_name: crm-web
    ports:
      - "8000:8000"
    env_file:
      - crm/.env
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./logs:/app/logs
      - ./crm/media:/app/media
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


  prometheus:
    image: prom/prometheus:latest
    container_name: crm-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web

  grafana:
    image: grafana/grafana:latest
    container_name: crm-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/dashboards/django_metrics.json:/var/lib/grafana/dashboards/django_metrics.json
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: crm-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: crm-promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./logs:/var/log/crm:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  postgres_data: