# Generated by Django 6.1 on 2026-08-29 07:30

from django.db import migrations


def create_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    roles_permissions = {
        "Operators": [
            "add_lead", "view_lead", "change_lead"
        ],
        "Marketers": [
            "add_service", "view_service", "change_service",
            "add_ad", "view_ad", "change_ad"
        ],
        "Managers": [
            "view_lead", "change_lead",
            "add_customer", "view_customer", "change_customer",
            "add_contract", "view_contract", "change_contract"
        ]
    }

    for role_name, permission_codenames in roles_permissions.items():
        group, created = Group.objects.get_or_create(name=role_name)

        django_permissions = Permission.objects.filter(codename__in=permission_codenames)

        group.permissions.set(django_permissions)


def remove_groups_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=["Operators", "Marketers", "Managers"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_options_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions, remove_groups_and_permissions),
    ]
