# Generated by Django 6.1 on 2026-08-27 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_remove_lead_responsible_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='leads.lead', verbose_name='Потенциальный клиент (лид)')),
            ],
            options={
                'verbose_name': 'Активный клиент',
                'verbose_name_plural': 'Активные клиенты',
            },
        ),
    ]
