# Generated by Django 6.1 on 2026-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если снять галочку, клиент уйдет в архив CRM', verbose_name='Активен'),
        ),
    ]
