# Generated by Django 6.1 on 2026-08-27 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название кампании')),
                ('channel', models.CharField(help_text='Например: Яндекс.Директ, Telegram, VK', max_length=100, verbose_name='Канал продвижения')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Бюджет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='Продвигаемая услуга')),
            ],
            options={
                'verbose_name': 'Рекламная кампания',
                'verbose_name_plural': 'Рекламные кампании',
                'ordering': ['-id'],
            },
        ),
    ]
