# Generated by Django 6.1 on 2026-08-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если снять галочку, продвижение прекратиться', verbose_name='Активна'),
        ),
    ]
