# Generated by Django 6.1 on 2026-08-29 10:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_created_at_ad_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Бюджет'),
        ),
    ]
