# Generated by Django 6.1 on 2026-08-27 09:57

import django.db.models.deletion
from django.db import migrations, models

import contracts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('customers', '0002_customer_is_active'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название контракта')),
                ('document', models.FileField(help_text='Загрузите подписанный скан договора (PDF, DOCX)',
                                              upload_to=contracts.models.upload_contract_document,
                                              verbose_name='Файл с документом')),
                ('start_date', models.DateField(verbose_name='Дата заключения')),
                ('end_date', models.DateField(verbose_name='Дата окончания действия')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в CRM')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено в CRM')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer',
                                               verbose_name='Клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service',
                                              verbose_name='Предоставляемая услуга')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-start_date'],
            },
        ),
    ]
