# Generated by Django 6.1 on 2026-08-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если снять галочку, контракт уйдет в архив',
                                      verbose_name='Активен'),
        ),
    ]
